/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppLayout {
    }
    interface AppProduct {
        "slug": string;
    }
    interface AppProducts {
        "page": number;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppProductElement extends Components.AppProduct, HTMLStencilElement {
    }
    var HTMLAppProductElement: {
        prototype: HTMLAppProductElement;
        new (): HTMLAppProductElement;
    };
    interface HTMLAppProductsElement extends Components.AppProducts, HTMLStencilElement {
    }
    var HTMLAppProductsElement: {
        prototype: HTMLAppProductsElement;
        new (): HTMLAppProductsElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-layout": HTMLAppLayoutElement;
        "app-product": HTMLAppProductElement;
        "app-products": HTMLAppProductsElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppLayout {
    }
    interface AppProduct {
        "slug"?: string;
    }
    interface AppProducts {
        "page"?: number;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-layout": AppLayout;
        "app-product": AppProduct;
        "app-products": AppProducts;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-layout": LocalJSX.AppLayout & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-product": LocalJSX.AppProduct & JSXBase.HTMLAttributes<HTMLAppProductElement>;
            "app-products": LocalJSX.AppProducts & JSXBase.HTMLAttributes<HTMLAppProductsElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
