/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Dragger } from "./components/corejam-canvas/canvas.machine";
export namespace Components {
    interface CanvasApp {
    }
    interface CorejamBuilder {
        "demo": boolean;
        "draggers": Dragger[];
    }
    interface CorejamCanvas {
    }
    interface CorejamDebugger {
        "machine": any;
    }
    interface CorejamDeploy {
    }
    interface CorejamEdit {
        "node": any;
    }
    interface RouteEditor {
    }
    interface RouteIndex {
    }
}
declare global {
    interface HTMLCanvasAppElement extends Components.CanvasApp, HTMLStencilElement {
    }
    var HTMLCanvasAppElement: {
        prototype: HTMLCanvasAppElement;
        new (): HTMLCanvasAppElement;
    };
    interface HTMLCorejamBuilderElement extends Components.CorejamBuilder, HTMLStencilElement {
    }
    var HTMLCorejamBuilderElement: {
        prototype: HTMLCorejamBuilderElement;
        new (): HTMLCorejamBuilderElement;
    };
    interface HTMLCorejamCanvasElement extends Components.CorejamCanvas, HTMLStencilElement {
    }
    var HTMLCorejamCanvasElement: {
        prototype: HTMLCorejamCanvasElement;
        new (): HTMLCorejamCanvasElement;
    };
    interface HTMLCorejamDebuggerElement extends Components.CorejamDebugger, HTMLStencilElement {
    }
    var HTMLCorejamDebuggerElement: {
        prototype: HTMLCorejamDebuggerElement;
        new (): HTMLCorejamDebuggerElement;
    };
    interface HTMLCorejamDeployElement extends Components.CorejamDeploy, HTMLStencilElement {
    }
    var HTMLCorejamDeployElement: {
        prototype: HTMLCorejamDeployElement;
        new (): HTMLCorejamDeployElement;
    };
    interface HTMLCorejamEditElement extends Components.CorejamEdit, HTMLStencilElement {
    }
    var HTMLCorejamEditElement: {
        prototype: HTMLCorejamEditElement;
        new (): HTMLCorejamEditElement;
    };
    interface HTMLRouteEditorElement extends Components.RouteEditor, HTMLStencilElement {
    }
    var HTMLRouteEditorElement: {
        prototype: HTMLRouteEditorElement;
        new (): HTMLRouteEditorElement;
    };
    interface HTMLRouteIndexElement extends Components.RouteIndex, HTMLStencilElement {
    }
    var HTMLRouteIndexElement: {
        prototype: HTMLRouteIndexElement;
        new (): HTMLRouteIndexElement;
    };
    interface HTMLElementTagNameMap {
        "canvas-app": HTMLCanvasAppElement;
        "corejam-builder": HTMLCorejamBuilderElement;
        "corejam-canvas": HTMLCorejamCanvasElement;
        "corejam-debugger": HTMLCorejamDebuggerElement;
        "corejam-deploy": HTMLCorejamDeployElement;
        "corejam-edit": HTMLCorejamEditElement;
        "route-editor": HTMLRouteEditorElement;
        "route-index": HTMLRouteIndexElement;
    }
}
declare namespace LocalJSX {
    interface CanvasApp {
    }
    interface CorejamBuilder {
        "demo"?: boolean;
        "draggers"?: Dragger[];
    }
    interface CorejamCanvas {
    }
    interface CorejamDebugger {
        "machine"?: any;
    }
    interface CorejamDeploy {
    }
    interface CorejamEdit {
        "node"?: any;
    }
    interface RouteEditor {
    }
    interface RouteIndex {
    }
    interface IntrinsicElements {
        "canvas-app": CanvasApp;
        "corejam-builder": CorejamBuilder;
        "corejam-canvas": CorejamCanvas;
        "corejam-debugger": CorejamDebugger;
        "corejam-deploy": CorejamDeploy;
        "corejam-edit": CorejamEdit;
        "route-editor": RouteEditor;
        "route-index": RouteIndex;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "canvas-app": LocalJSX.CanvasApp & JSXBase.HTMLAttributes<HTMLCanvasAppElement>;
            "corejam-builder": LocalJSX.CorejamBuilder & JSXBase.HTMLAttributes<HTMLCorejamBuilderElement>;
            "corejam-canvas": LocalJSX.CorejamCanvas & JSXBase.HTMLAttributes<HTMLCorejamCanvasElement>;
            "corejam-debugger": LocalJSX.CorejamDebugger & JSXBase.HTMLAttributes<HTMLCorejamDebuggerElement>;
            "corejam-deploy": LocalJSX.CorejamDeploy & JSXBase.HTMLAttributes<HTMLCorejamDeployElement>;
            "corejam-edit": LocalJSX.CorejamEdit & JSXBase.HTMLAttributes<HTMLCorejamEditElement>;
            "route-editor": LocalJSX.RouteEditor & JSXBase.HTMLAttributes<HTMLRouteEditorElement>;
            "route-index": LocalJSX.RouteIndex & JSXBase.HTMLAttributes<HTMLRouteIndexElement>;
        }
    }
}
