coverage:
  status:
    project:
      default:
        target: 70
        threshold: 0%
    patch: off
  fixes:
    - "examples/nextjs/__LINKEDPKGS__/base::packages/base" # move path   e.g., "before/path" => "after/path"
