coverage:
  status:
    project:
      default:
        target: 75
        threshold: 0%
    patch: off
  fixes:
    - "__LINKEDPKGS__/base::packages/base" # move path   e.g., "before/path" => "after/path"