/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AuthAccount {
    }
    interface AuthAdminUserForm {
        "error": boolean;
        "formId": string;
    }
    interface AuthAdminUserList {
        "data": any;
        "page": number;
    }
    interface AuthApp {
    }
    interface AuthFormLogin {
        "onFail": Function;
        "onSuccess": Function;
    }
    interface AuthFormRegister {
        "onFail": Function;
        "onSuccess": Function;
    }
    interface AuthHeader {
    }
    interface AuthReset {
    }
    interface AuthResetPasswordForm {
    }
    interface AuthRouteAccount {
    }
    interface AuthRouteAdmin {
        "param": any;
    }
    interface AuthRouteAdminIndex {
    }
    interface AuthRouteAdminUserForm {
        "param": any;
    }
    interface AuthRouteIndex {
    }
    interface AuthRouteLogin {
    }
    interface AuthRouteRegister {
    }
    interface AuthRouteReset {
    }
    interface AuthRouteVerify {
    }
    interface AuthVerify {
    }
    interface CorejamIconsAccount {
    }
    interface CorejamIdentity {
        "loginLink": string;
        "registerLink": string;
    }
}
declare global {
    interface HTMLAuthAccountElement extends Components.AuthAccount, HTMLStencilElement {
    }
    var HTMLAuthAccountElement: {
        prototype: HTMLAuthAccountElement;
        new (): HTMLAuthAccountElement;
    };
    interface HTMLAuthAdminUserFormElement extends Components.AuthAdminUserForm, HTMLStencilElement {
    }
    var HTMLAuthAdminUserFormElement: {
        prototype: HTMLAuthAdminUserFormElement;
        new (): HTMLAuthAdminUserFormElement;
    };
    interface HTMLAuthAdminUserListElement extends Components.AuthAdminUserList, HTMLStencilElement {
    }
    var HTMLAuthAdminUserListElement: {
        prototype: HTMLAuthAdminUserListElement;
        new (): HTMLAuthAdminUserListElement;
    };
    interface HTMLAuthAppElement extends Components.AuthApp, HTMLStencilElement {
    }
    var HTMLAuthAppElement: {
        prototype: HTMLAuthAppElement;
        new (): HTMLAuthAppElement;
    };
    interface HTMLAuthFormLoginElement extends Components.AuthFormLogin, HTMLStencilElement {
    }
    var HTMLAuthFormLoginElement: {
        prototype: HTMLAuthFormLoginElement;
        new (): HTMLAuthFormLoginElement;
    };
    interface HTMLAuthFormRegisterElement extends Components.AuthFormRegister, HTMLStencilElement {
    }
    var HTMLAuthFormRegisterElement: {
        prototype: HTMLAuthFormRegisterElement;
        new (): HTMLAuthFormRegisterElement;
    };
    interface HTMLAuthHeaderElement extends Components.AuthHeader, HTMLStencilElement {
    }
    var HTMLAuthHeaderElement: {
        prototype: HTMLAuthHeaderElement;
        new (): HTMLAuthHeaderElement;
    };
    interface HTMLAuthResetElement extends Components.AuthReset, HTMLStencilElement {
    }
    var HTMLAuthResetElement: {
        prototype: HTMLAuthResetElement;
        new (): HTMLAuthResetElement;
    };
    interface HTMLAuthResetPasswordFormElement extends Components.AuthResetPasswordForm, HTMLStencilElement {
    }
    var HTMLAuthResetPasswordFormElement: {
        prototype: HTMLAuthResetPasswordFormElement;
        new (): HTMLAuthResetPasswordFormElement;
    };
    interface HTMLAuthRouteAccountElement extends Components.AuthRouteAccount, HTMLStencilElement {
    }
    var HTMLAuthRouteAccountElement: {
        prototype: HTMLAuthRouteAccountElement;
        new (): HTMLAuthRouteAccountElement;
    };
    interface HTMLAuthRouteAdminElement extends Components.AuthRouteAdmin, HTMLStencilElement {
    }
    var HTMLAuthRouteAdminElement: {
        prototype: HTMLAuthRouteAdminElement;
        new (): HTMLAuthRouteAdminElement;
    };
    interface HTMLAuthRouteAdminIndexElement extends Components.AuthRouteAdminIndex, HTMLStencilElement {
    }
    var HTMLAuthRouteAdminIndexElement: {
        prototype: HTMLAuthRouteAdminIndexElement;
        new (): HTMLAuthRouteAdminIndexElement;
    };
    interface HTMLAuthRouteAdminUserFormElement extends Components.AuthRouteAdminUserForm, HTMLStencilElement {
    }
    var HTMLAuthRouteAdminUserFormElement: {
        prototype: HTMLAuthRouteAdminUserFormElement;
        new (): HTMLAuthRouteAdminUserFormElement;
    };
    interface HTMLAuthRouteIndexElement extends Components.AuthRouteIndex, HTMLStencilElement {
    }
    var HTMLAuthRouteIndexElement: {
        prototype: HTMLAuthRouteIndexElement;
        new (): HTMLAuthRouteIndexElement;
    };
    interface HTMLAuthRouteLoginElement extends Components.AuthRouteLogin, HTMLStencilElement {
    }
    var HTMLAuthRouteLoginElement: {
        prototype: HTMLAuthRouteLoginElement;
        new (): HTMLAuthRouteLoginElement;
    };
    interface HTMLAuthRouteRegisterElement extends Components.AuthRouteRegister, HTMLStencilElement {
    }
    var HTMLAuthRouteRegisterElement: {
        prototype: HTMLAuthRouteRegisterElement;
        new (): HTMLAuthRouteRegisterElement;
    };
    interface HTMLAuthRouteResetElement extends Components.AuthRouteReset, HTMLStencilElement {
    }
    var HTMLAuthRouteResetElement: {
        prototype: HTMLAuthRouteResetElement;
        new (): HTMLAuthRouteResetElement;
    };
    interface HTMLAuthRouteVerifyElement extends Components.AuthRouteVerify, HTMLStencilElement {
    }
    var HTMLAuthRouteVerifyElement: {
        prototype: HTMLAuthRouteVerifyElement;
        new (): HTMLAuthRouteVerifyElement;
    };
    interface HTMLAuthVerifyElement extends Components.AuthVerify, HTMLStencilElement {
    }
    var HTMLAuthVerifyElement: {
        prototype: HTMLAuthVerifyElement;
        new (): HTMLAuthVerifyElement;
    };
    interface HTMLCorejamIconsAccountElement extends Components.CorejamIconsAccount, HTMLStencilElement {
    }
    var HTMLCorejamIconsAccountElement: {
        prototype: HTMLCorejamIconsAccountElement;
        new (): HTMLCorejamIconsAccountElement;
    };
    interface HTMLCorejamIdentityElement extends Components.CorejamIdentity, HTMLStencilElement {
    }
    var HTMLCorejamIdentityElement: {
        prototype: HTMLCorejamIdentityElement;
        new (): HTMLCorejamIdentityElement;
    };
    interface HTMLElementTagNameMap {
        "auth-account": HTMLAuthAccountElement;
        "auth-admin-user-form": HTMLAuthAdminUserFormElement;
        "auth-admin-user-list": HTMLAuthAdminUserListElement;
        "auth-app": HTMLAuthAppElement;
        "auth-form-login": HTMLAuthFormLoginElement;
        "auth-form-register": HTMLAuthFormRegisterElement;
        "auth-header": HTMLAuthHeaderElement;
        "auth-reset": HTMLAuthResetElement;
        "auth-reset-password-form": HTMLAuthResetPasswordFormElement;
        "auth-route-account": HTMLAuthRouteAccountElement;
        "auth-route-admin": HTMLAuthRouteAdminElement;
        "auth-route-admin-index": HTMLAuthRouteAdminIndexElement;
        "auth-route-admin-user-form": HTMLAuthRouteAdminUserFormElement;
        "auth-route-index": HTMLAuthRouteIndexElement;
        "auth-route-login": HTMLAuthRouteLoginElement;
        "auth-route-register": HTMLAuthRouteRegisterElement;
        "auth-route-reset": HTMLAuthRouteResetElement;
        "auth-route-verify": HTMLAuthRouteVerifyElement;
        "auth-verify": HTMLAuthVerifyElement;
        "corejam-icons-account": HTMLCorejamIconsAccountElement;
        "corejam-identity": HTMLCorejamIdentityElement;
    }
}
declare namespace LocalJSX {
    interface AuthAccount {
    }
    interface AuthAdminUserForm {
        "error"?: boolean;
        "formId"?: string;
    }
    interface AuthAdminUserList {
        "data"?: any;
        "page"?: number;
    }
    interface AuthApp {
    }
    interface AuthFormLogin {
        "onFail"?: Function;
        "onSuccess"?: Function;
    }
    interface AuthFormRegister {
        "onFail"?: Function;
        "onSuccess"?: Function;
    }
    interface AuthHeader {
    }
    interface AuthReset {
    }
    interface AuthResetPasswordForm {
    }
    interface AuthRouteAccount {
    }
    interface AuthRouteAdmin {
        "param"?: any;
    }
    interface AuthRouteAdminIndex {
    }
    interface AuthRouteAdminUserForm {
        "param"?: any;
    }
    interface AuthRouteIndex {
    }
    interface AuthRouteLogin {
    }
    interface AuthRouteRegister {
    }
    interface AuthRouteReset {
    }
    interface AuthRouteVerify {
    }
    interface AuthVerify {
    }
    interface CorejamIconsAccount {
    }
    interface CorejamIdentity {
        "loginLink"?: string;
        "registerLink"?: string;
    }
    interface IntrinsicElements {
        "auth-account": AuthAccount;
        "auth-admin-user-form": AuthAdminUserForm;
        "auth-admin-user-list": AuthAdminUserList;
        "auth-app": AuthApp;
        "auth-form-login": AuthFormLogin;
        "auth-form-register": AuthFormRegister;
        "auth-header": AuthHeader;
        "auth-reset": AuthReset;
        "auth-reset-password-form": AuthResetPasswordForm;
        "auth-route-account": AuthRouteAccount;
        "auth-route-admin": AuthRouteAdmin;
        "auth-route-admin-index": AuthRouteAdminIndex;
        "auth-route-admin-user-form": AuthRouteAdminUserForm;
        "auth-route-index": AuthRouteIndex;
        "auth-route-login": AuthRouteLogin;
        "auth-route-register": AuthRouteRegister;
        "auth-route-reset": AuthRouteReset;
        "auth-route-verify": AuthRouteVerify;
        "auth-verify": AuthVerify;
        "corejam-icons-account": CorejamIconsAccount;
        "corejam-identity": CorejamIdentity;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "auth-account": LocalJSX.AuthAccount & JSXBase.HTMLAttributes<HTMLAuthAccountElement>;
            "auth-admin-user-form": LocalJSX.AuthAdminUserForm & JSXBase.HTMLAttributes<HTMLAuthAdminUserFormElement>;
            "auth-admin-user-list": LocalJSX.AuthAdminUserList & JSXBase.HTMLAttributes<HTMLAuthAdminUserListElement>;
            "auth-app": LocalJSX.AuthApp & JSXBase.HTMLAttributes<HTMLAuthAppElement>;
            "auth-form-login": LocalJSX.AuthFormLogin & JSXBase.HTMLAttributes<HTMLAuthFormLoginElement>;
            "auth-form-register": LocalJSX.AuthFormRegister & JSXBase.HTMLAttributes<HTMLAuthFormRegisterElement>;
            "auth-header": LocalJSX.AuthHeader & JSXBase.HTMLAttributes<HTMLAuthHeaderElement>;
            "auth-reset": LocalJSX.AuthReset & JSXBase.HTMLAttributes<HTMLAuthResetElement>;
            "auth-reset-password-form": LocalJSX.AuthResetPasswordForm & JSXBase.HTMLAttributes<HTMLAuthResetPasswordFormElement>;
            "auth-route-account": LocalJSX.AuthRouteAccount & JSXBase.HTMLAttributes<HTMLAuthRouteAccountElement>;
            "auth-route-admin": LocalJSX.AuthRouteAdmin & JSXBase.HTMLAttributes<HTMLAuthRouteAdminElement>;
            "auth-route-admin-index": LocalJSX.AuthRouteAdminIndex & JSXBase.HTMLAttributes<HTMLAuthRouteAdminIndexElement>;
            "auth-route-admin-user-form": LocalJSX.AuthRouteAdminUserForm & JSXBase.HTMLAttributes<HTMLAuthRouteAdminUserFormElement>;
            "auth-route-index": LocalJSX.AuthRouteIndex & JSXBase.HTMLAttributes<HTMLAuthRouteIndexElement>;
            "auth-route-login": LocalJSX.AuthRouteLogin & JSXBase.HTMLAttributes<HTMLAuthRouteLoginElement>;
            "auth-route-register": LocalJSX.AuthRouteRegister & JSXBase.HTMLAttributes<HTMLAuthRouteRegisterElement>;
            "auth-route-reset": LocalJSX.AuthRouteReset & JSXBase.HTMLAttributes<HTMLAuthRouteResetElement>;
            "auth-route-verify": LocalJSX.AuthRouteVerify & JSXBase.HTMLAttributes<HTMLAuthRouteVerifyElement>;
            "auth-verify": LocalJSX.AuthVerify & JSXBase.HTMLAttributes<HTMLAuthVerifyElement>;
            "corejam-icons-account": LocalJSX.CorejamIconsAccount & JSXBase.HTMLAttributes<HTMLCorejamIconsAccountElement>;
            "corejam-identity": LocalJSX.CorejamIdentity & JSXBase.HTMLAttributes<HTMLCorejamIdentityElement>;
        }
    }
}
