/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AuthAdminUserForm {
        "error": boolean;
        "formId": string;
    }
    interface AuthAdminUserList {
        "data": any;
        "page": number;
    }
    interface AuthResetPasswordForm {
    }
    interface CjRouteAdmin {
        "param": any;
    }
    interface CjRouteAdminIndex {
    }
    interface CjRouteAdminUserForm {
        "param": any;
    }
    interface CjRouteIndex {
    }
    interface CjRouteLogin {
    }
    interface CjRouteRegister {
    }
    interface CorejamAuthAccount {
    }
    interface CorejamAuthFormLogin {
        "onFail": Function;
        "onSuccess": Function;
    }
    interface CorejamAuthFormRegister {
        "onFail": Function;
        "onSuccess": Function;
    }
    interface CorejamAuthHeader {
    }
    interface CorejamAuthRouteVerify {
    }
    interface CorejamAuthVerify {
    }
    interface CorejamIconsAccount {
    }
    interface CorejamIdentity {
        "loginLink": string;
        "registerLink": string;
    }
}
declare global {
    interface HTMLAuthAdminUserFormElement extends Components.AuthAdminUserForm, HTMLStencilElement {
    }
    var HTMLAuthAdminUserFormElement: {
        prototype: HTMLAuthAdminUserFormElement;
        new (): HTMLAuthAdminUserFormElement;
    };
    interface HTMLAuthAdminUserListElement extends Components.AuthAdminUserList, HTMLStencilElement {
    }
    var HTMLAuthAdminUserListElement: {
        prototype: HTMLAuthAdminUserListElement;
        new (): HTMLAuthAdminUserListElement;
    };
    interface HTMLAuthResetPasswordFormElement extends Components.AuthResetPasswordForm, HTMLStencilElement {
    }
    var HTMLAuthResetPasswordFormElement: {
        prototype: HTMLAuthResetPasswordFormElement;
        new (): HTMLAuthResetPasswordFormElement;
    };
    interface HTMLCjRouteAdminElement extends Components.CjRouteAdmin, HTMLStencilElement {
    }
    var HTMLCjRouteAdminElement: {
        prototype: HTMLCjRouteAdminElement;
        new (): HTMLCjRouteAdminElement;
    };
    interface HTMLCjRouteAdminIndexElement extends Components.CjRouteAdminIndex, HTMLStencilElement {
    }
    var HTMLCjRouteAdminIndexElement: {
        prototype: HTMLCjRouteAdminIndexElement;
        new (): HTMLCjRouteAdminIndexElement;
    };
    interface HTMLCjRouteAdminUserFormElement extends Components.CjRouteAdminUserForm, HTMLStencilElement {
    }
    var HTMLCjRouteAdminUserFormElement: {
        prototype: HTMLCjRouteAdminUserFormElement;
        new (): HTMLCjRouteAdminUserFormElement;
    };
    interface HTMLCjRouteIndexElement extends Components.CjRouteIndex, HTMLStencilElement {
    }
    var HTMLCjRouteIndexElement: {
        prototype: HTMLCjRouteIndexElement;
        new (): HTMLCjRouteIndexElement;
    };
    interface HTMLCjRouteLoginElement extends Components.CjRouteLogin, HTMLStencilElement {
    }
    var HTMLCjRouteLoginElement: {
        prototype: HTMLCjRouteLoginElement;
        new (): HTMLCjRouteLoginElement;
    };
    interface HTMLCjRouteRegisterElement extends Components.CjRouteRegister, HTMLStencilElement {
    }
    var HTMLCjRouteRegisterElement: {
        prototype: HTMLCjRouteRegisterElement;
        new (): HTMLCjRouteRegisterElement;
    };
    interface HTMLCorejamAuthAccountElement extends Components.CorejamAuthAccount, HTMLStencilElement {
    }
    var HTMLCorejamAuthAccountElement: {
        prototype: HTMLCorejamAuthAccountElement;
        new (): HTMLCorejamAuthAccountElement;
    };
    interface HTMLCorejamAuthFormLoginElement extends Components.CorejamAuthFormLogin, HTMLStencilElement {
    }
    var HTMLCorejamAuthFormLoginElement: {
        prototype: HTMLCorejamAuthFormLoginElement;
        new (): HTMLCorejamAuthFormLoginElement;
    };
    interface HTMLCorejamAuthFormRegisterElement extends Components.CorejamAuthFormRegister, HTMLStencilElement {
    }
    var HTMLCorejamAuthFormRegisterElement: {
        prototype: HTMLCorejamAuthFormRegisterElement;
        new (): HTMLCorejamAuthFormRegisterElement;
    };
    interface HTMLCorejamAuthHeaderElement extends Components.CorejamAuthHeader, HTMLStencilElement {
    }
    var HTMLCorejamAuthHeaderElement: {
        prototype: HTMLCorejamAuthHeaderElement;
        new (): HTMLCorejamAuthHeaderElement;
    };
    interface HTMLCorejamAuthRouteVerifyElement extends Components.CorejamAuthRouteVerify, HTMLStencilElement {
    }
    var HTMLCorejamAuthRouteVerifyElement: {
        prototype: HTMLCorejamAuthRouteVerifyElement;
        new (): HTMLCorejamAuthRouteVerifyElement;
    };
    interface HTMLCorejamAuthVerifyElement extends Components.CorejamAuthVerify, HTMLStencilElement {
    }
    var HTMLCorejamAuthVerifyElement: {
        prototype: HTMLCorejamAuthVerifyElement;
        new (): HTMLCorejamAuthVerifyElement;
    };
    interface HTMLCorejamIconsAccountElement extends Components.CorejamIconsAccount, HTMLStencilElement {
    }
    var HTMLCorejamIconsAccountElement: {
        prototype: HTMLCorejamIconsAccountElement;
        new (): HTMLCorejamIconsAccountElement;
    };
    interface HTMLCorejamIdentityElement extends Components.CorejamIdentity, HTMLStencilElement {
    }
    var HTMLCorejamIdentityElement: {
        prototype: HTMLCorejamIdentityElement;
        new (): HTMLCorejamIdentityElement;
    };
    interface HTMLElementTagNameMap {
        "auth-admin-user-form": HTMLAuthAdminUserFormElement;
        "auth-admin-user-list": HTMLAuthAdminUserListElement;
        "auth-reset-password-form": HTMLAuthResetPasswordFormElement;
        "cj-route-admin": HTMLCjRouteAdminElement;
        "cj-route-admin-index": HTMLCjRouteAdminIndexElement;
        "cj-route-admin-user-form": HTMLCjRouteAdminUserFormElement;
        "cj-route-index": HTMLCjRouteIndexElement;
        "cj-route-login": HTMLCjRouteLoginElement;
        "cj-route-register": HTMLCjRouteRegisterElement;
        "corejam-auth-account": HTMLCorejamAuthAccountElement;
        "corejam-auth-form-login": HTMLCorejamAuthFormLoginElement;
        "corejam-auth-form-register": HTMLCorejamAuthFormRegisterElement;
        "corejam-auth-header": HTMLCorejamAuthHeaderElement;
        "corejam-auth-route-verify": HTMLCorejamAuthRouteVerifyElement;
        "corejam-auth-verify": HTMLCorejamAuthVerifyElement;
        "corejam-icons-account": HTMLCorejamIconsAccountElement;
        "corejam-identity": HTMLCorejamIdentityElement;
    }
}
declare namespace LocalJSX {
    interface AuthAdminUserForm {
        "error"?: boolean;
        "formId"?: string;
    }
    interface AuthAdminUserList {
        "data"?: any;
        "page"?: number;
    }
    interface AuthResetPasswordForm {
    }
    interface CjRouteAdmin {
        "param"?: any;
    }
    interface CjRouteAdminIndex {
    }
    interface CjRouteAdminUserForm {
        "param"?: any;
    }
    interface CjRouteIndex {
    }
    interface CjRouteLogin {
    }
    interface CjRouteRegister {
    }
    interface CorejamAuthAccount {
    }
    interface CorejamAuthFormLogin {
        "onFail"?: Function;
        "onSuccess"?: Function;
    }
    interface CorejamAuthFormRegister {
        "onFail"?: Function;
        "onSuccess"?: Function;
    }
    interface CorejamAuthHeader {
    }
    interface CorejamAuthRouteVerify {
    }
    interface CorejamAuthVerify {
    }
    interface CorejamIconsAccount {
    }
    interface CorejamIdentity {
        "loginLink"?: string;
        "registerLink"?: string;
    }
    interface IntrinsicElements {
        "auth-admin-user-form": AuthAdminUserForm;
        "auth-admin-user-list": AuthAdminUserList;
        "auth-reset-password-form": AuthResetPasswordForm;
        "cj-route-admin": CjRouteAdmin;
        "cj-route-admin-index": CjRouteAdminIndex;
        "cj-route-admin-user-form": CjRouteAdminUserForm;
        "cj-route-index": CjRouteIndex;
        "cj-route-login": CjRouteLogin;
        "cj-route-register": CjRouteRegister;
        "corejam-auth-account": CorejamAuthAccount;
        "corejam-auth-form-login": CorejamAuthFormLogin;
        "corejam-auth-form-register": CorejamAuthFormRegister;
        "corejam-auth-header": CorejamAuthHeader;
        "corejam-auth-route-verify": CorejamAuthRouteVerify;
        "corejam-auth-verify": CorejamAuthVerify;
        "corejam-icons-account": CorejamIconsAccount;
        "corejam-identity": CorejamIdentity;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "auth-admin-user-form": LocalJSX.AuthAdminUserForm & JSXBase.HTMLAttributes<HTMLAuthAdminUserFormElement>;
            "auth-admin-user-list": LocalJSX.AuthAdminUserList & JSXBase.HTMLAttributes<HTMLAuthAdminUserListElement>;
            "auth-reset-password-form": LocalJSX.AuthResetPasswordForm & JSXBase.HTMLAttributes<HTMLAuthResetPasswordFormElement>;
            "cj-route-admin": LocalJSX.CjRouteAdmin & JSXBase.HTMLAttributes<HTMLCjRouteAdminElement>;
            "cj-route-admin-index": LocalJSX.CjRouteAdminIndex & JSXBase.HTMLAttributes<HTMLCjRouteAdminIndexElement>;
            "cj-route-admin-user-form": LocalJSX.CjRouteAdminUserForm & JSXBase.HTMLAttributes<HTMLCjRouteAdminUserFormElement>;
            "cj-route-index": LocalJSX.CjRouteIndex & JSXBase.HTMLAttributes<HTMLCjRouteIndexElement>;
            "cj-route-login": LocalJSX.CjRouteLogin & JSXBase.HTMLAttributes<HTMLCjRouteLoginElement>;
            "cj-route-register": LocalJSX.CjRouteRegister & JSXBase.HTMLAttributes<HTMLCjRouteRegisterElement>;
            "corejam-auth-account": LocalJSX.CorejamAuthAccount & JSXBase.HTMLAttributes<HTMLCorejamAuthAccountElement>;
            "corejam-auth-form-login": LocalJSX.CorejamAuthFormLogin & JSXBase.HTMLAttributes<HTMLCorejamAuthFormLoginElement>;
            "corejam-auth-form-register": LocalJSX.CorejamAuthFormRegister & JSXBase.HTMLAttributes<HTMLCorejamAuthFormRegisterElement>;
            "corejam-auth-header": LocalJSX.CorejamAuthHeader & JSXBase.HTMLAttributes<HTMLCorejamAuthHeaderElement>;
            "corejam-auth-route-verify": LocalJSX.CorejamAuthRouteVerify & JSXBase.HTMLAttributes<HTMLCorejamAuthRouteVerifyElement>;
            "corejam-auth-verify": LocalJSX.CorejamAuthVerify & JSXBase.HTMLAttributes<HTMLCorejamAuthVerifyElement>;
            "corejam-icons-account": LocalJSX.CorejamIconsAccount & JSXBase.HTMLAttributes<HTMLCorejamIconsAccountElement>;
            "corejam-identity": LocalJSX.CorejamIdentity & JSXBase.HTMLAttributes<HTMLCorejamIdentityElement>;
        }
    }
}
