/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CanvasLayout {
    }
    interface CorejamCanvas {
        "canvas": any;
        "draggers": string[];
    }
    interface CorejamEdit {
        "node": any;
    }
    interface RouteIndex {
    }
}
declare global {
    interface HTMLCanvasLayoutElement extends Components.CanvasLayout, HTMLStencilElement {
    }
    var HTMLCanvasLayoutElement: {
        prototype: HTMLCanvasLayoutElement;
        new (): HTMLCanvasLayoutElement;
    };
    interface HTMLCorejamCanvasElement extends Components.CorejamCanvas, HTMLStencilElement {
    }
    var HTMLCorejamCanvasElement: {
        prototype: HTMLCorejamCanvasElement;
        new (): HTMLCorejamCanvasElement;
    };
    interface HTMLCorejamEditElement extends Components.CorejamEdit, HTMLStencilElement {
    }
    var HTMLCorejamEditElement: {
        prototype: HTMLCorejamEditElement;
        new (): HTMLCorejamEditElement;
    };
    interface HTMLRouteIndexElement extends Components.RouteIndex, HTMLStencilElement {
    }
    var HTMLRouteIndexElement: {
        prototype: HTMLRouteIndexElement;
        new (): HTMLRouteIndexElement;
    };
    interface HTMLElementTagNameMap {
        "canvas-layout": HTMLCanvasLayoutElement;
        "corejam-canvas": HTMLCorejamCanvasElement;
        "corejam-edit": HTMLCorejamEditElement;
        "route-index": HTMLRouteIndexElement;
    }
}
declare namespace LocalJSX {
    interface CanvasLayout {
    }
    interface CorejamCanvas {
        "canvas"?: any;
        "draggers"?: string[];
    }
    interface CorejamEdit {
        "node"?: any;
    }
    interface RouteIndex {
    }
    interface IntrinsicElements {
        "canvas-layout": CanvasLayout;
        "corejam-canvas": CorejamCanvas;
        "corejam-edit": CorejamEdit;
        "route-index": RouteIndex;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "canvas-layout": LocalJSX.CanvasLayout & JSXBase.HTMLAttributes<HTMLCanvasLayoutElement>;
            "corejam-canvas": LocalJSX.CorejamCanvas & JSXBase.HTMLAttributes<HTMLCorejamCanvasElement>;
            "corejam-edit": LocalJSX.CorejamEdit & JSXBase.HTMLAttributes<HTMLCorejamEditElement>;
            "route-index": LocalJSX.RouteIndex & JSXBase.HTMLAttributes<HTMLRouteIndexElement>;
        }
    }
}
