/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CanvasLayout {
    }
    interface CorejamCanvas {
        "canvas": any;
    }
    interface CorejamCanvasEditor {
        "draggers": string[];
    }
    interface CorejamDebugger {
        "machine": any;
    }
    interface CorejamEdit {
        "node": any;
    }
    interface CorejamTab {
        "header": string;
    }
    interface CorejamTabs {
    }
    interface CorejamTest {
    }
    interface RouteIndex {
    }
}
declare global {
    interface HTMLCanvasLayoutElement extends Components.CanvasLayout, HTMLStencilElement {
    }
    var HTMLCanvasLayoutElement: {
        prototype: HTMLCanvasLayoutElement;
        new (): HTMLCanvasLayoutElement;
    };
    interface HTMLCorejamCanvasElement extends Components.CorejamCanvas, HTMLStencilElement {
    }
    var HTMLCorejamCanvasElement: {
        prototype: HTMLCorejamCanvasElement;
        new (): HTMLCorejamCanvasElement;
    };
    interface HTMLCorejamCanvasEditorElement extends Components.CorejamCanvasEditor, HTMLStencilElement {
    }
    var HTMLCorejamCanvasEditorElement: {
        prototype: HTMLCorejamCanvasEditorElement;
        new (): HTMLCorejamCanvasEditorElement;
    };
    interface HTMLCorejamDebuggerElement extends Components.CorejamDebugger, HTMLStencilElement {
    }
    var HTMLCorejamDebuggerElement: {
        prototype: HTMLCorejamDebuggerElement;
        new (): HTMLCorejamDebuggerElement;
    };
    interface HTMLCorejamEditElement extends Components.CorejamEdit, HTMLStencilElement {
    }
    var HTMLCorejamEditElement: {
        prototype: HTMLCorejamEditElement;
        new (): HTMLCorejamEditElement;
    };
    interface HTMLCorejamTabElement extends Components.CorejamTab, HTMLStencilElement {
    }
    var HTMLCorejamTabElement: {
        prototype: HTMLCorejamTabElement;
        new (): HTMLCorejamTabElement;
    };
    interface HTMLCorejamTabsElement extends Components.CorejamTabs, HTMLStencilElement {
    }
    var HTMLCorejamTabsElement: {
        prototype: HTMLCorejamTabsElement;
        new (): HTMLCorejamTabsElement;
    };
    interface HTMLCorejamTestElement extends Components.CorejamTest, HTMLStencilElement {
    }
    var HTMLCorejamTestElement: {
        prototype: HTMLCorejamTestElement;
        new (): HTMLCorejamTestElement;
    };
    interface HTMLRouteIndexElement extends Components.RouteIndex, HTMLStencilElement {
    }
    var HTMLRouteIndexElement: {
        prototype: HTMLRouteIndexElement;
        new (): HTMLRouteIndexElement;
    };
    interface HTMLElementTagNameMap {
        "canvas-layout": HTMLCanvasLayoutElement;
        "corejam-canvas": HTMLCorejamCanvasElement;
        "corejam-canvas-editor": HTMLCorejamCanvasEditorElement;
        "corejam-debugger": HTMLCorejamDebuggerElement;
        "corejam-edit": HTMLCorejamEditElement;
        "corejam-tab": HTMLCorejamTabElement;
        "corejam-tabs": HTMLCorejamTabsElement;
        "corejam-test": HTMLCorejamTestElement;
        "route-index": HTMLRouteIndexElement;
    }
}
declare namespace LocalJSX {
    interface CanvasLayout {
    }
    interface CorejamCanvas {
        "canvas"?: any;
    }
    interface CorejamCanvasEditor {
        "draggers"?: string[];
    }
    interface CorejamDebugger {
        "machine"?: any;
    }
    interface CorejamEdit {
        "node"?: any;
    }
    interface CorejamTab {
        "header"?: string;
    }
    interface CorejamTabs {
    }
    interface CorejamTest {
    }
    interface RouteIndex {
    }
    interface IntrinsicElements {
        "canvas-layout": CanvasLayout;
        "corejam-canvas": CorejamCanvas;
        "corejam-canvas-editor": CorejamCanvasEditor;
        "corejam-debugger": CorejamDebugger;
        "corejam-edit": CorejamEdit;
        "corejam-tab": CorejamTab;
        "corejam-tabs": CorejamTabs;
        "corejam-test": CorejamTest;
        "route-index": RouteIndex;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "canvas-layout": LocalJSX.CanvasLayout & JSXBase.HTMLAttributes<HTMLCanvasLayoutElement>;
            "corejam-canvas": LocalJSX.CorejamCanvas & JSXBase.HTMLAttributes<HTMLCorejamCanvasElement>;
            "corejam-canvas-editor": LocalJSX.CorejamCanvasEditor & JSXBase.HTMLAttributes<HTMLCorejamCanvasEditorElement>;
            "corejam-debugger": LocalJSX.CorejamDebugger & JSXBase.HTMLAttributes<HTMLCorejamDebuggerElement>;
            "corejam-edit": LocalJSX.CorejamEdit & JSXBase.HTMLAttributes<HTMLCorejamEditElement>;
            "corejam-tab": LocalJSX.CorejamTab & JSXBase.HTMLAttributes<HTMLCorejamTabElement>;
            "corejam-tabs": LocalJSX.CorejamTabs & JSXBase.HTMLAttributes<HTMLCorejamTabsElement>;
            "corejam-test": LocalJSX.CorejamTest & JSXBase.HTMLAttributes<HTMLCorejamTestElement>;
            "route-index": LocalJSX.RouteIndex & JSXBase.HTMLAttributes<HTMLRouteIndexElement>;
        }
    }
}
