/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppLiveview {
    }
    interface AppPlayground {
        "cmp": string;
        "data": any;
    }
    interface AppRoot {
    }
    interface AppRouter {
        "docs": any;
        "mode": string;
        "routes": any;
    }
    interface AppTestComp {
    }
    interface AppWelcome {
        "mode": string;
        "routes": any;
    }
}
declare global {
    interface HTMLAppLiveviewElement extends Components.AppLiveview, HTMLStencilElement {
    }
    var HTMLAppLiveviewElement: {
        prototype: HTMLAppLiveviewElement;
        new (): HTMLAppLiveviewElement;
    };
    interface HTMLAppPlaygroundElement extends Components.AppPlayground, HTMLStencilElement {
    }
    var HTMLAppPlaygroundElement: {
        prototype: HTMLAppPlaygroundElement;
        new (): HTMLAppPlaygroundElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppRouterElement extends Components.AppRouter, HTMLStencilElement {
    }
    var HTMLAppRouterElement: {
        prototype: HTMLAppRouterElement;
        new (): HTMLAppRouterElement;
    };
    interface HTMLAppTestCompElement extends Components.AppTestComp, HTMLStencilElement {
    }
    var HTMLAppTestCompElement: {
        prototype: HTMLAppTestCompElement;
        new (): HTMLAppTestCompElement;
    };
    interface HTMLAppWelcomeElement extends Components.AppWelcome, HTMLStencilElement {
    }
    var HTMLAppWelcomeElement: {
        prototype: HTMLAppWelcomeElement;
        new (): HTMLAppWelcomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-liveview": HTMLAppLiveviewElement;
        "app-playground": HTMLAppPlaygroundElement;
        "app-root": HTMLAppRootElement;
        "app-router": HTMLAppRouterElement;
        "app-test-comp": HTMLAppTestCompElement;
        "app-welcome": HTMLAppWelcomeElement;
    }
}
declare namespace LocalJSX {
    interface AppLiveview {
    }
    interface AppPlayground {
        "cmp"?: string;
        "data"?: any;
    }
    interface AppRoot {
    }
    interface AppRouter {
        "docs"?: any;
        "mode"?: string;
        "routes"?: any;
    }
    interface AppTestComp {
    }
    interface AppWelcome {
        "mode"?: string;
        "routes"?: any;
    }
    interface IntrinsicElements {
        "app-liveview": AppLiveview;
        "app-playground": AppPlayground;
        "app-root": AppRoot;
        "app-router": AppRouter;
        "app-test-comp": AppTestComp;
        "app-welcome": AppWelcome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-liveview": LocalJSX.AppLiveview & JSXBase.HTMLAttributes<HTMLAppLiveviewElement>;
            "app-playground": LocalJSX.AppPlayground & JSXBase.HTMLAttributes<HTMLAppPlaygroundElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-router": LocalJSX.AppRouter & JSXBase.HTMLAttributes<HTMLAppRouterElement>;
            "app-test-comp": LocalJSX.AppTestComp & JSXBase.HTMLAttributes<HTMLAppTestCompElement>;
            "app-welcome": LocalJSX.AppWelcome & JSXBase.HTMLAttributes<HTMLAppWelcomeElement>;
        }
    }
}
