/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CorejamApp {
    }
    interface CorejamRouter {
    }
}
declare global {
    interface HTMLCorejamAppElement extends Components.CorejamApp, HTMLStencilElement {
    }
    var HTMLCorejamAppElement: {
        prototype: HTMLCorejamAppElement;
        new (): HTMLCorejamAppElement;
    };
    interface HTMLCorejamRouterElement extends Components.CorejamRouter, HTMLStencilElement {
    }
    var HTMLCorejamRouterElement: {
        prototype: HTMLCorejamRouterElement;
        new (): HTMLCorejamRouterElement;
    };
    interface HTMLElementTagNameMap {
        "corejam-app": HTMLCorejamAppElement;
        "corejam-router": HTMLCorejamRouterElement;
    }
}
declare namespace LocalJSX {
    interface CorejamApp {
    }
    interface CorejamRouter {
    }
    interface IntrinsicElements {
        "corejam-app": CorejamApp;
        "corejam-router": CorejamRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "corejam-app": LocalJSX.CorejamApp & JSXBase.HTMLAttributes<HTMLCorejamAppElement>;
            "corejam-router": LocalJSX.CorejamRouter & JSXBase.HTMLAttributes<HTMLCorejamRouterElement>;
        }
    }
}
